version: '3.8'

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local

services:
  mysql-db:
    image: mysql
    container_name: mysql
    build: mysql
    volumes:
      - mysql_data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: dummy_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: P@ssw0rd
    restart: always
    expose:
      - 3306

  postgres-db:
    image: postgres
    container_name: postgres
    build: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: dummy_db
    restart: always
    expose:
      - 5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    expose:
      - 8080

  proxy:
    image: nginx:latest
    container_name: nginx
    build: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx/logs:rw
    depends_on:
      - mysql-db
      - postgres-db
      - adminer
    ports:
      - 3306:3306
      - 5432:5432
      - 8080:8080
    restart: unless-stopped